# Generated by Django 4.2.20 on 2025-07-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('monto_prestamo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duracion_prestamo', models.PositiveIntegerField(help_text='Duración en meses')),
                ('tipo_prestamo', models.CharField(max_length=100)),
                ('fecha_prestamo', models.DateField()),
                ('dia_cobro', models.DateField()),
                ('interes_mensual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('numero_cuotas', models.PositiveIntegerField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_interes_pagar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_total_pagar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='clientes.cliente')),
            ],
        ),
    ]
