# Generated by Django 4.2.20 on 2026-03-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_interes_mensual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['numero']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('pagado', 'Pagado')], default='vigente', help_text='Estado actual del credito', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='interes_acumulado',
            field=models.CharField(default='0', help_text='Suma de todos los pagos de interes registrados', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='prestamo_sin_cronograma',
            field=models.BooleanField(default=False, help_text='True si el prestamo no genera cuotas individuales'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_pagado_cuotas_sin_cronograma',
            field=models.CharField(default='0', help_text='Acumulado de pagos en modo sin cronograma', max_length=100),
        ),
        migrations.AddField(
            model_name='cuota',
            name='abonado',
            field=models.CharField(default='0', help_text='Monto pagado en esta cuota', max_length=100),
        ),
        migrations.AddField(
            model_name='cuota',
            name='numero',
            field=models.PositiveIntegerField(default=0, help_text='Numero secuencial de la cuota (1, 2, 3...)'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='saldo',
            field=models.CharField(default='0', help_text='Monto pendiente de esta cuota', max_length=100),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('interes', 'Interés'), ('liquidacion', 'Liquidación')], default='interes', max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_intereses', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('cuota', 'Pago de Cuota'), ('cuota_sin_cronograma', 'Pago de Cuota Sin Cronograma'), ('interes', 'Pago de Interés'), ('saldo_total', 'Pago de Saldo Total'), ('calculado', 'Pago Calculado')], max_length=30)),
                ('monto', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.cliente')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='clientes.cuota')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creacion', 'Creación'), ('pago', 'Pago'), ('eliminacion_pago', 'Eliminación de Pago'), ('cambio_fecha', 'Cambio de Fecha'), ('ampliacion', 'Ampliación'), ('liquidacion', 'Liquidación'), ('cambio_plazo', 'Cambio de Plazo')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('monto', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ampliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_adicional', models.CharField(max_length=100)),
                ('nueva_tasa', models.CharField(max_length=100)),
                ('nuevas_cuotas', models.PositiveIntegerField()),
                ('capital_anterior', models.CharField(max_length=100)),
                ('capital_nuevo', models.CharField(max_length=100)),
                ('interes_liquidacion', models.CharField(max_length=100)),
                ('saldo_favor', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampliaciones', to='clientes.cliente')),
            ],
        ),
    ]
