# Generated by Django 4.2.20 on 2026-03-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cuota_options_cliente_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('pagado', 'Pagado'), ('perdido', 'Perdido')], default='vigente', help_text='Estado actual del credito', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialevento',
            name='tipo',
            field=models.CharField(choices=[('creacion', 'Creación'), ('pago', 'Pago'), ('eliminacion_pago', 'Eliminación de Pago'), ('cambio_fecha', 'Cambio de Fecha'), ('ampliacion', 'Ampliación'), ('liquidacion', 'Liquidación'), ('cambio_plazo', 'Cambio de Plazo'), ('cambio_estado', 'Cambio de Estado')], max_length=30),
        ),
    ]
