# Generated by Django 4.2.20 on 2026-05-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_pagosaldototalsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción/nota de los pagos aplicados a esta cuota'),
        ),
    ]
