# Generated by Django 4.2.20 on 2026-05-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cuota_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='dias_mora',
            field=models.IntegerField(default=0, help_text='Dias de mora = fecha_pago_real - fecha_proximo_pago (minimo 0)'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago_real',
            field=models.DateField(blank=True, help_text='Fecha real en que se realizo el pago', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_proximo_pago',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento esperada de la cuota', null=True),
        ),
    ]
