# Generated by Django 4.2.20 on 2026-06-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_pago_dias_mora_pago_fecha_pago_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='fecha_proximo_pago',
            field=models.DateField(blank=True, help_text='Fecha que el cliente promete pagar (no cambia el vencimiento real fecha_pago). La mora = fecha_proximo_pago - fecha_pago', null=True),
        ),
    ]
