# Generated by Django 4.2.20 on 2026-06-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cuota_fecha_proximo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='dias_mora',
            field=models.IntegerField(default=0, help_text='Dias de mora = fecha_proximo_pago - fecha_pago_real (minimo 0)'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago_real',
            field=models.DateField(blank=True, help_text='Vencimiento real de la cuota en la que se debia', null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_proximo_pago',
            field=models.DateField(blank=True, help_text='Fecha de referencia del pago (promesa del cliente u hoy)', null=True),
        ),
    ]
